(function(g){var window=this;var EEa=function(a,b){return g.Tb(a,b)},l6=function(a){g.cn(a,"zx",g.vb());
return a},m6=function(a,b,c){g.wa(c)||(c=[String(c)]);
g.fn(a.o,b,c)},FEa=function(a,b){var c=[];
g.Qk(b,function(a){try{var b=g.HD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.GD(b)&&c.push(a):c.push(a)},a);
return c},GEa=function(a,b){var c=FEa(a,b);
(0,g.D)(c,function(a){g.HD.prototype.remove.call(this,a)},a)},HEa=function(a){if(a.Md){if(a.Md.locationOverrideToken)return{locationOverrideToken:a.Md.locationOverrideToken};
if(null!=a.Md.latitudeE7&&null!=a.Md.longitudeE7)return{latitudeE7:a.Md.latitudeE7,longitudeE7:a.Md.longitudeE7}}return null},IEa=function(a,b,c,d){var e=new g.Um(null,void 0);
a&&g.Vm(e,a);b&&g.Wm(e,b);c&&g.Xm(e,c);d&&g.Ym(e,d);return e},JEa=function(a){g.qG[a]&&(a=g.qG[a],(0,g.D)(a,function(a){g.oG[a]&&delete g.oG[a]}),a.length=0)},KEa=function(a){var b=g.nG();
if(b)if(b.clear(a),a)JEa(a);else for(var c in g.qG)JEa(c)},n6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Om;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",LEa(this,a.capabilities||""),MEa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},LEa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Ca(EEa,NEa)).forEach(function(b){a.capabilities.add(b)})},MEa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},o6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},p6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},OEa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},PEa=function(a){return new o6(a)},QEa=function(a){return g.wa(a)?(0,g.J)(a,PEa):[]},q6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},r6=function(a){return g.wa(a)?"["+(0,g.J)(a,q6).join(",")+"]":"null"},s6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},REa=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},t6=function(a,b){return g.Ja(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},u6=function(a,b){return g.Ja(a,function(a){return p6(a,b)})},SEa=function(){var a=(0,g.zH)();
a&&GEa(a,a.o.fe(!0))},v6=function(){var a=g.CH("yt-remote-connected-devices")||[];
g.eb(a);return a},TEa=function(a){if(g.Pa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.J)(a,function(a,b){return 0==b?a:a.substring(c.length)})},UEa=function(a){g.BH("yt-remote-connected-devices",a,86400)},x6=function(){if(w6)return w6;
var a=g.CH("yt-remote-device-id");a||(a=s6(),g.BH("yt-remote-device-id",a,31536E3));for(var b=v6(),c=1,d=a;g.Na(b,d);)c++,d=a+"#"+c;return w6=d},y6=function(){var a=v6(),b=x6();
g.Na(a,b);g.EH()&&g.gb(a,b);a=TEa(a);if(g.Pa(a))try{g.YG("remote_sid")}catch(c){}else try{g.XG("remote_sid",a.join(","),-1)}catch(c){}},VEa=function(){return g.CH("yt-remote-session-browser-channel")},WEa=function(){return g.CH("yt-remote-local-screens")||[]},XEa=function(){g.BH("yt-remote-lounge-token-expiration",!0,86400)},YEa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.J)(WEa(),function(a){return a.loungeToken}),c=(0,g.J)(a,function(a){return a.loungeToken});
(0,g.Cm)(c,function(a){return!g.Na(b,a)})&&XEa();
g.BH("yt-remote-local-screens",a,31536E3)},ZEa=function(a,b){g.BH("yt-remote-session-browser-channel",a);
g.BH("yt-remote-session-screen-id",b);var c=v6(),d=x6();g.Na(c,d)||c.push(d);UEa(c);y6()},z6=function(a){a||(g.DH("yt-remote-session-screen-id"),g.DH("yt-remote-session-video-id"));
y6();a=v6();g.Ta(a,x6());UEa(a)},$Ea=function(){if(!A6){var a=g.SD();
a&&(A6=new g.BD(a))}return A6?!!A6.get("yt-remote-use-staging-server"):!1},aFa=function(){var a=window.document.createElement("a");
g.id(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.zb(a)},bFa=function(a,b,c){c=void 0===c?null:c;
var d=g.Rd("SCRIPT");d.id=a;d.onload=function(){b&&(0,window.setTimeout)(b,0)};
d.onreadystatechange=function(){switch(d.readyState){case "loaded":case "complete":d.onload()}};
c&&d.setAttribute("nonce",c);g.kd(d,g.pe("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));a=window.document.getElementsByTagName("head")[0]||window.document.body;a.insertBefore(d,a.firstChild);return d},cFa=function(a){a=void 0===a?null:a;
var b=aFa(),c=window.document.getElementById(b),d=c&&g.xF(c,"loaded");d||c&&!d||(c=bFa(b,function(){g.xF(c,"loaded")||(g.wF(c,"loaded","true"),g.uG(b),g.xE(g.Ca(KEa,b),0))},a))},dFa=function(){var a=void 0===a?null:a;
window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):cFa(a)},B6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},eFa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},C6=function(a){a.length?fFa(a.shift(),function(){C6(a)}):D6()},gFa=function(a){return"chrome-extension://"+a+E6},fFa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},F6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},D6=function(){var a=eFa();
a&&a(!1,"No cast extension found")},G6=function(){if(hFa){var a=2,b=eFa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;fFa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",D6,c)}},iFa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(G6(),a({command:"cast.sender.init"}))},jFa=function(){G6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);C6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+E6,"//www.gstatic.com/eureka/clank"+E6])},H6=function(a,b,c){g.L.call(this);
this.F=null!=c?(0,g.B)(a,c):a;this.Ed=b;this.D=(0,g.B)(this.fL,this);this.o=!1;this.A=0;this.B=this.Ga=null;this.C=[]},I6=function(){},J6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.kn(this);this.A=new g.Bg;this.A.setInterval(250)},lFa=function(a,b,c){a.Uj=1;
a.yh=l6(b.clone());a.fj=c;a.D=!0;kFa(a,null)},K6=function(a,b,c,d,e){a.Uj=1;
a.yh=l6(b.clone());a.fj=null;a.D=c;e&&(a.sF=!1);kFa(a,d)},kFa=function(a,b){a.Rk=(0,g.H)();
L6(a);a.Yh=a.yh.clone();m6(a.Yh,"t",a.F);a.Bn=0;a.Wc=a.o.Ms(a.o.qn()?b:null);0<a.Et&&(a.Jq=new g.vl((0,g.B)(a.OG,a,a.Wc),a.Et));a.Y.W(a.Wc,"readystatechange",a.DW);var c=a.Di?g.cc(a.Di):{};a.fj?(a.xr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Wc.send(a.Yh,a.xr,a.fj,c)):(a.xr="GET",a.sF&&!g.Ld&&(c.Connection="close"),a.Wc.send(a.Yh,a.xr,null,c));a.o.Gf(1)},oFa=function(a,b,c){for(var d=!0;!a.mi&&a.Bn<c.length;){var e=mFa(a,c);
if(e==M6){4==b&&(a.zh=4,N6(15),d=!1);break}else if(e==nFa){a.zh=4;N6(16);d=!1;break}else O6(a,e)}4==b&&0==c.length&&(a.zh=1,N6(17),d=!1);a.Nf=a.Nf&&d;d||(P6(a),Q6(a))},mFa=function(a,b){var c=a.Bn,d=b.indexOf("\n",c);
if(-1==d)return M6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return nFa;d+=1;if(d+c>b.length)return M6;var e=b.substr(d,c);a.Bn=d+c;return e},qFa=function(a,b){a.Rk=(0,g.H)();
L6(a);var c=b?window.location.hostname:"";a.Yh=a.yh.clone();g.cn(a.Yh,"DOMAIN",c);g.cn(a.Yh,"t",a.F);try{a.Of=new window.ActiveXObject("htmlfile")}catch(n){P6(a);a.zh=7;N6(22);Q6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in R6)k=R6[l];else if(l in pFa)k=R6[l]=pFa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=R6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.ld(g.Ac("b/12014412"),d+"</body></html>");a.Of.open();a.Of.write(g.bd(c));a.Of.close();a.Of.parentWindow.m=(0,g.B)(a.HV,a);a.Of.parentWindow.d=(0,g.B)(a.BE,a,!0);a.Of.parentWindow.rpcClose=(0,g.B)(a.BE,a,!1);c=a.Of.createElement("DIV");a.Of.parentWindow.document.body.appendChild(c);d=g.Pc(a.Yh.toString());d=g.ob(g.Mc(d));d=g.ld(g.Ac("b/12014412"),'<iframe src="'+d+'"></iframe>');g.hd(c,g.bd(d));a.o.Gf(1)},
L6=function(a){a.wx=(0,g.H)()+a.C;
rFa(a,a.C)},rFa=function(a,b){if(null!=a.ol)throw Error("WatchDog timer not null");
a.ol=S6((0,g.B)(a.XV,a),b)},T6=function(a){a.ol&&(g.x.clearTimeout(a.ol),a.ol=null)},Q6=function(a){a.o.HA()||a.mi||a.o.rq(a)},P6=function(a){T6(a);
g.mf(a.Jq);a.Jq=null;a.A.stop();g.qn(a.Y);if(a.Wc){var b=a.Wc;a.Wc=null;b.abort();b.dispose()}a.Of&&(a.Of=null)},O6=function(a,b){try{a.o.tE(a,b),a.o.Gf(4)}catch(c){}},tFa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;sFa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){tFa(a,b,c,d,f)},f)})}},sFa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{U6(d),c(!0)}catch(e){}};
d.onerror=function(){try{U6(d),c(!1)}catch(e){}};
d.onabort=function(){try{U6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{U6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},U6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},uFa=function(a){this.o=a;
this.A=new I6},vFa=function(a){var b=V6(a.o,a.ul,"/mail/images/cleardot.gif");
l6(b);tFa(b.toString(),5E3,(0,g.B)(a.kK,a),3,2E3);a.Gf(1)},X6=function(a){var b=a.o.J;
if(null!=b)N6(5),b?(N6(11),W6(a.o,a,!1)):(N6(12),W6(a.o,a,!0));else if(a.Ie=new J6(a,void 0,void 0,void 0),a.Ie.Di=a.Ct,b=a.o,b=V6(b,b.qn()?a.fm:null,a.Dt),N6(5),!g.Jd||g.sc(10))m6(b,"TYPE","xmlhttp"),K6(a.Ie,b,!1,a.fm,!1);else{m6(b,"TYPE","html");var c=a.Ie;a=!!a.fm;c.Uj=3;c.yh=l6(b.clone());qFa(c,a)}},Y6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new I6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},wFa=function(a,b){this.o=a;
this.map=b;this.context=null},xFa=function(a){g.of.call(this,"statevent",a)},yFa=function(a,b){g.of.call(this,"timingevent",a);
this.size=b},zFa=function(a){g.of.call(this,"serverreachability",a)},CFa=function(a){AFa(a);
if(3==a.o){var b=a.Ym++,c=a.Zo.clone();g.cn(c,"SID",a.B);g.cn(c,"RID",b);g.cn(c,"TYPE","terminate");Z6(a,c);b=new J6(a,a.B,b,void 0);b.Uj=2;b.yh=l6(c.clone());(new window.Image).src=b.yh;b.Rk=(0,g.H)();L6(b)}BFa(a)},DFa=function(a){a.GK(1,0);
a.Zo=V6(a,null,a.Bt);$6(a)},AFa=function(a){a.ph&&(a.ph.abort(),a.ph=null);
a.yc&&(a.yc.cancel(),a.yc=null);a.zg&&(g.x.clearTimeout(a.zg),a.zg=null);a7(a);a.ke&&(a.ke.cancel(),a.ke=null);a.sh&&(g.x.clearTimeout(a.sh),a.sh=null)},EFa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new wFa(a.rR++,b));2!=a.o&&3!=a.o||$6(a)},$6=function(a){a.ke||a.sh||(a.sh=S6((0,g.B)(a.zE,a),0),a.Kj=0)},GFa=function(a,b){if(1==a.o){if(!b){a.Ym=Math.floor(1E5*Math.random());
var c=a.Ym++,d=new J6(a,"",c,void 0);d.Di=null;var e=b7(a),f=a.Zo.clone();g.cn(f,"RID",c);g.cn(f,"CVER","1");Z6(a,f);lFa(d,f,e);a.ke=d;a.o=2}}else 3==a.o&&(b?FFa(a,b):0==a.A.length||a.ke||FFa(a))},FFa=function(a,b){if(b)if(6<a.oi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.Ym-1;var d=b7(a)}else c=b.G,d=b.fj;else c=a.Ym++,d=b7(a);var e=a.Zo.clone();g.cn(e,"SID",a.B);g.cn(e,"RID",c);g.cn(e,"AID",a.lk);Z6(a,e);c=new J6(a,a.B,c,a.Kj+1);c.Di=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ke=c;lFa(c,e,d)},Z6=function(a,b){if(a.Dd){var c=a.Dd.nA();
c&&g.Hb(c,function(a,c){g.cn(b,c,a)})}},b7=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.oi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.oi?e:f-d;try{g.Hb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},HFa=function(a){a.yc||a.zg||(a.G=1,a.zg=S6((0,g.B)(a.yE,a),0),a.xj=0)},c7=function(a){if(a.yc||a.zg||3<=a.xj)return!1;
a.G++;a.zg=S6((0,g.B)(a.yE,a),IFa(a,a.xj));a.xj++;return!0},W6=function(a,b,c){a.vr=c;
a.Zf=b.Mg;a.F||DFa(a)},a7=function(a){null!=a.pi&&(g.x.clearTimeout(a.pi),a.pi=null)},IFa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},d7=function(a,b){if(2==b||9==b){var c=null;
a.Dd&&(c=null);var d=(0,g.B)(a.sX,a);c||(c=new g.Um("//www.google.com/images/cleardot.gif"),l6(c));sFa(c.toString(),1E4,d)}else N6(2);JFa(a,b)},JFa=function(a,b){a.o=0;
a.Dd&&a.Dd.nz(b);BFa(a);AFa(a)},BFa=function(a){a.o=0;
a.Zf=-1;if(a.Dd)if(0==a.C.length&&0==a.A.length)a.Dd.xs();else{g.Wa(a.C);var b=g.Wa(a.A);a.C.length=0;a.A.length=0;a.Dd.xs(b)}},V6=function(a,b,c){var d=g.dn(c);
if(""!=d.A)b&&g.Wm(d,b+"."+d.A),g.Xm(d,d.D);else{var e=window.location;d=IEa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Kl&&g.Hb(a.Kl,function(a,b){g.cn(d,b,a)});
g.cn(d,"VER",a.oi);Z6(a,d);return d},S6=function(a,b){if(!g.ya(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},N6=function(a){e7.dispatchEvent(new xFa(e7,a))},KFa=function(){},LFa=function(a,b){this.action=a;
this.params=b||{}},f7=function(a,b){g.L.call(this);
this.o=new g.Cu(this.xV,0,this);g.M(this,this.o);this.Ed=5E3;this.A=0;if(g.ya(a))b&&(a=(0,g.B)(a,b));else if(a&&g.ya(a.handleEvent))a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},g7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.AD;this.A=new f7(this.YX,this);this.o=this.ib=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.M=c||!1},MFa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.vr,sessionId:a.o.B,arrayId:a.o.lk}},NFa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&GFa(a.o),CFa(a.o));a.H=0},h7=function(a){return!!a.o&&3==a.o.o},OFa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},i7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Qg(a)||"";b&&(this.port=":"+b);this.domain=g.Pg(a)||"";a=g.Fb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.yb(a,"10.0")&&(this.A=!1))},j7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.Zg(c+b,{})},k7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ca(a.C,d,!0),onError:g.Ca(a.B,e),Id:g.Ca(a.D,e)};c&&(a.Ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.OE(b,a)},SFa=function(){var a=PFa;
QFa();l7.push(a);RFa(l7)},m7=function(a,b){QFa();
var c=l7,d=TFa(a,String(b));g.Pa(c)?UFa(d):(RFa(c),(0,g.D)(c,function(a){a(d)}))},QFa=function(){l7||(l7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ta("yt.mdx.remote.debug.handlers_",l7,void 0))},UFa=function(a){var b=(n7+1)%50;
n7=b;o7[b]=a;p7||(p7=49==b)},RFa=function(a){var b=o7;
if(b[0]){var c=n7,d=p7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);
o7=Array(50);n7=-1;p7=!1}},TFa=function(a,b){var c=((0,g.H)()-VFa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},q7=function(a){g.eG.call(this);
this.G=a;this.o=[]},WFa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},XFa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Yd)(a.o,function(a){return!!t6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=WFa(a,b[d])||c;return c},YFa=function(a,b){var c=a.o.length;
a.o=(0,g.Yd)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},r7=function(a,b,c,d){g.eG.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ga=window.NaN},t7=function(a){q7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;s7(this);this.info("Initializing with "+r6(this.o))},ZFa=function(a){if(a.o.length){var b=(0,g.J)(a.o,function(a){return a.id}),c=j7(a.B,"/pairing/get_lounge_token_batch");
k7(a.B,c,{screen_ids:b.join(",")},(0,g.B)(a.sL,a),(0,g.B)(a.rL,a))}},s7=function(a){var b=QEa(WEa());
b=(0,g.Yd)(b,function(a){return!a.uuid});
return XFa(a,b)},u7=function(a,b){YEa((0,g.J)(a.o,OEa));
b&&XEa()},w7=function(a,b){g.eG.call(this);
this.F=b;var c=g.CH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Na(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;v7("Initialized with "+g.Hg(this.o))},$Fa=function(a,b,c){var d=j7(a.D,"/pairing/get_screen_availability");
k7(a.D,d,{lounge_token:b.token},(0,g.B)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},x7=function(a,b){a:if(g.Nb(b)!=g.Nb(a.o))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(v7("Updated online screens: "+g.Hg(a.o)),a.o=b,a.U("screenChange"));aGa(a)},y7=function(a){(0,window.isNaN)(a.B)||g.zE(a.B);
a.B=g.xE((0,g.B)(a.xw,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},v7=function(a){m7("OnlineScreenService",a)},bGa=function(a){var b={};
(0,g.D)(a.F(),function(a){a.token?b[a.token]=a.id:this.sc("Requesting availability of screen w/o lounge token.")});
return b},aGa=function(a){a=g.Qb(g.Ib(a.o,function(a){return a}));
g.eb(a);a.length?g.BH("yt-remote-online-screen-ids",a.join(","),60):g.DH("yt-remote-online-screen-ids")},z7=function(a){q7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};cGa(this)},eGa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.De();if(k=(c?u6(k,c):null)||u6(k,b)){k.uuid=b;var l=A7(a,k);$Fa(a.A,l,function(a){e(a?l:null)})}else c?dGa(a,c,(0,g.B)(function(a){var f=A7(this,new o6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));$Fa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},fGa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},dGa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.OE(j7(a.F,"/pairing/get_lounge_token_batch"),e)},gGa=function(a){a.o=a.B.De();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+r6(a.o))},cGa=function(a){B7(a);
a.B=new t7(a.F);a.B.subscribe("screenChange",(0,g.B)(a.HL,a));gGa(a);a.C=QEa(g.CH("yt-remote-automatic-screen-cache")||[]);B7(a);a.info("Initializing automatic screens: "+r6(a.C));a.A=new w7(a.F,(0,g.B)(a.De,a,!0));a.A.subscribe("screenChange",(0,g.B)(function(){this.U("onlineScreenChange")},a))},A7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=u6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.BH("yt-remote-automatic-screen-cache",(0,g.J)(a.C,OEa)));B7(a);a.D[b.uuid]=b.id;g.BH("yt-remote-device-id-map",a.D,31536E3);return b},B7=function(a){a.D=g.CH("yt-remote-device-id-map")||{}},C7=function(a,b,c){g.eG.call(this);
this.M=c;this.J=a;this.A=b;this.B=null},D7=function(a,b){m7(a.M,b)},E7=function(a,b){C7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.B)(this.eY,this);this.D=(0,g.B)(this.jW,this);this.C=g.xE((0,g.B)(function(){hGa(this,null)},this),12E4)},iGa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Hg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.A,(0,g.B)(function(){D7(this,"Failed to send message: getMdxSessionStatus.")},a)):D7(a,"Sending yt message without session: "+g.Hg(b))},hGa=function(a,b){g.zE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.B)(a.tq,a),d=(0,g.B)(a.He,a);a.xA(b,c,d,5)}}else a.He(Error("Waiting for session status timed out."))},F7=function(a,b,c){C7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.A;this.F=window.NaN;this.L=(0,g.B)(this.hY,this);this.o=g.A},jGa=function(a){a.o=a.J.XG(a.K,a.A.label,a.A.friendlyName,(0,g.B)(function(a){this.o=g.A;
this.tq(a)},a),(0,g.B)(function(a){this.o=g.A;
this.He(a)},a))},kGa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}$Ea()&&(b.env_useStageMdx=1);return g.Xg(b)},G7=function(a,b){C7.call(this,a,b,"ManualSession");
this.o=g.xE((0,g.B)(this.nk,this,null),150)},H7=function(a,b,c,d){g.eG.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.B)(this.JU,this)},lGa=function(a,b){return b?g.Ja(a.B,function(a){return p6(b,a.label)},a):null},I7=function(a){m7("Controller",a)},PFa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},J7=function(a){return a.D||!!a.B.length||!!a.o},K7=function(a,b,c){b!=a.o&&(g.mf(a.o),(a.o=b)?(c?a.U("yt-remote-cast2-receiver-resumed",b.A):a.U("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.B)(a.wE,a,b)),b.B?a.U("yt-remote-cast2-session-change",b.B):c&&a.o.nk(null)):a.U("yt-remote-cast2-session-change",null))},mGa=function(a){var b=a.A.WG(),c=a.o&&a.o.A;
a=(0,g.J)(b,function(a){c&&p6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=lGa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},sGa=function(a,b,c,d,e,f,k){nGa()?oGa(b,e,f,k)&&(M7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?pGa(a,c):(window.__onGCastApiAvailable=function(b,d){b?pGa(a,c):(N7("Failed to load cast API: "+d),O7(!1),M7(!1),g.DH("yt-remote-cast-available"),g.DH("yt-remote-cast-receiver"),qGa(),
c(!1))},d?dFa():F6("CriOS")?iFa():F6("Android")&&F6("Chrome/")&&window.navigator.presentation?jFa():window.chrome&&window.navigator.presentation&&!F6("Edge")?(G6(),C6(rGa.map(gFa))):D6())):L7("Cannot initialize because not running Chrome")},qGa=function(){L7("dispose");
var a=P7();a&&a.dispose();g.ta("yt.mdx.remote.cloudview.instance_",null,void 0);tGa(!1);g.sG(Q7);Q7.length=0},R7=function(){return!!g.CH("yt-remote-cast-installed")},uGa=function(){var a=g.CH("yt-remote-cast-receiver");
return a?a.friendlyName:null},vGa=function(){L7("clearCurrentReceiver");
g.DH("yt-remote-cast-receiver")},wGa=function(){return R7()?P7()?P7().getCastSession():(N7("getCastSelector: Cast is not initialized."),null):(N7("getCastSelector: Cast API is not installed!"),null)},T7=function(){R7()?P7()?S7()?(L7("Requesting cast selector."),P7().requestSession()):(L7("Wait for cast API to be ready to request the session."),Q7.push(g.rG("yt-remote-cast2-api-ready",T7))):N7("requestCastSelector: Cast is not initialized."):N7("requestCastSelector: Cast API is not installed!")},U7=
function(a,b){S7()?P7().setConnectedScreenStatus(a,b):N7("setConnectedScreenStatus called before ready.")},nGa=function(){var a=0<=g.Fb.search(/ (CrMo|Chrome|CriOS)\//);
return g.RI||a},xGa=function(a,b){P7().init(a,b)},oGa=function(a,b,c,d){var e=!1;
P7()||(a=new H7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.BH("yt-remote-cast-available",a);g.vG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){L7("onReceiverSelected: "+a.friendlyName);
g.BH("yt-remote-cast-receiver",a);g.vG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){L7("onReceiverResumed: "+a.friendlyName);
g.BH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){L7("onSessionChange: "+q6(a));
a||g.DH("yt-remote-cast-receiver");g.vG("yt-remote-cast2-session-change",a)}),g.ta("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
L7("cloudview.createSingleton_: "+e);return e},P7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},pGa=function(a,b){O7(!0);
M7(!1);xGa(a,function(a){a?(tGa(!0),g.uG("yt-remote-cast2-api-ready")):(N7("Failed to initialize cast API."),O7(!1),g.DH("yt-remote-cast-available"),g.DH("yt-remote-cast-receiver"),qGa());b(a)})},L7=function(a){m7("cloudview",a)},N7=function(a){m7("cloudview",a)},O7=function(a){L7("setCastInstalled_ "+a);
g.BH("yt-remote-cast-installed",a)},S7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},tGa=function(a){L7("setApiReady_ "+a);
g.ta("yt.mdx.remote.cloudview.apiReady_",a,void 0)},M7=function(a){g.ta("yt.mdx.remote.cloudview.initializing_",a,void 0)},V7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.eg=!1;this.J=this.H=this.A=this.C=0;this.B=window.NaN;this.D=!1;this.reset(a)},W7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.eg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.H)();a.C=0;a.A=0;a.H=0;a.J=0;a.B=window.NaN;a.D=!1},X7=function(a){return a.sb()?((0,g.H)()-a.F)/1E3:0},Y7=function(a,b){a.G=b;
a.F=(0,g.H)()},Z7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},$7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&W7(a)},a8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.o);b.hasPrevious=a.eg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},c8=function(a,b){g.eG.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.QC;this.B=this.A=null;this.J=(0,g.B)(this.bS,this);this.G=(0,g.B)(this.bn,this);this.H=(0,g.B)(this.aS,this);this.K=(0,g.B)(this.oS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ex,this),yGa(this))):c=3;0!=c&&(b?this.Ex(c):g.xE((0,g.B)(function(){this.Ex(c)},this),0));
var d=wGa();d&&b8(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},d8=function(a){return new V7(a.C.getPlayerContextData())},yGa=function(a){(0,g.D)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Ca(this.EU,a),this))},a)},zGa=function(a){(0,g.D)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},e8=function(a,b){50>a.D.zc()&&g.SC(a.D,b)},g8=function(a,b,c){var d=d8(a);
Y7(d,c);-1E3!=d.playerState&&(d.playerState=b);f8(a,d)},h8=function(a,b,c){a.C.sendMessage(b,c)},f8=function(a,b){zGa(a);
a.C.setPlayerContextData(a8(b));yGa(a)},b8=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.bn(null));
a.B=b;a.B&&(m7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.bn(a.B.media[0]))},AGa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=d8(a);b.contentId!=d.videoId&&m7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;Y7(d,a.A.getEstimatedTime());f8(a,d)}else m7("CP","No cast media video. Ignoring state update.")},i8=function(a,b,c){return(0,g.B)(function(a){this.sc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.sc("Retrying "+b+" using MDx browser channel."),h8(this,b,c))},a)},j8=function(a,b,c){g.eG.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.M=window.NaN;this.V=[];this.C=this.G=this.B=this.jb=this.o=null;this.pa=a;this.V.push(g.OF(window,"beforeunload",(0,g.B)(this.jL,this)));this.A=[];this.jb=new V7;this.ba=b.id;this.o=BGa(this,c);this.o.subscribe("handlerOpened",this.fS,this);this.o.subscribe("handlerClosed",this.cS,this);this.o.subscribe("handlerError",this.dS,this);this.o.subscribe("handlerMessage",this.eS,this);OFa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.jb.videoId;g.EH()&&g.BH("yt-remote-session-video-id",a)},this)},k8=function(a){m7("conn",a)},BGa=function(a,b){return new g7(j7(a.pa,"/bc"),b)},l8=function(a,b){a.U("proxyStateChange",b)},CGa=function(a){a.D=g.xE((0,g.B)(function(){k8("Connecting timeout");
this.F(1)},a),2E4)},m8=function(a){g.zE(a.D);
a.D=window.NaN},n8=function(a){g.zE(a.M);
a.M=window.NaN},DGa=function(a){o8(a);
a.L=g.xE((0,g.B)(function(){p8(this,"getNowPlaying")},a),2E4)},o8=function(a){g.zE(a.L);
a.L=window.NaN},FGa=function(a,b){b&&(m8(a),n8(a));
b==(h7(a.o)&&(0,window.isNaN)(a.D))?b&&(l8(a,1),p8(a,"getSubtitlesTrack")):b?(a.Z()&&a.jb.reset(),l8(a,1),p8(a,"getNowPlaying"),EGa(a)):a.F(1)},GGa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.jb.videoId&&(g.Yb(b.params)?a.jb.o=null:a.jb.o=b.params,a.U("remotePlayerChange"))},HGa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.jb.listId=b.params.listId||a.jb.listId;$7(a.jb,c,d);a.U("remoteQueueChange")},JGa=function(a,b){b.params=b.params||{};
HGa(a,b);IGa(a,b);a.U("autoplayDismissed")},IGa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
Y7(a.jb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.jb.playerState&&(c=-1E3);a.jb.playerState=c;c=Number(b.params.loadedTime);a.jb.J=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.jb.H=(0,window.isNaN)(c)?0:c;c=a.jb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=(0,window.isNaN)(d)?!1:!0;c=a.jb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=(0,window.isNaN)(d)?0:d;c.A=(0,window.isNaN)(e)?0:
e;1==a.jb.playerState?DGa(a):o8(a);a.U("remotePlayerChange")},KGa=function(a,b){if(-1E3!=a.jb.playerState){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.jb.playerState=c;c=(0,window.parseInt)(b.params.currentTime,10);Y7(a.jb,(0,window.isNaN)(c)?0:c);a.U("remotePlayerChange")}},LGa=function(a,b){var c="true"==b.params.muted;
a.jb.volume=(0,window.parseInt)(b.params.volume,10);a.jb.muted=c;a.U("remotePlayerChange")},MGa=function(a,b){a.G=b.params.videoId;
a.U("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},NGa=function(a,b){var c="true"==b.params.hasNext;
a.jb.eg="true"==b.params.hasPrevious;a.jb.hasNext=c;a.U("previousNextChange")},EGa=function(a){g.zE(a.K);
a.K=g.xE((0,g.B)(a.F,a,1),864E5)},p8=function(a,b,c){c?k8("Sending: action="+b+", params="+g.Hg(c)):k8("Sending: action="+b);
a.o.sendMessage(b,c)},q8=function(a){q7.call(this,"ScreenServiceProxy");
this.nd=a;this.A=[];this.A.push(this.nd.$_s("screenChange",(0,g.B)(this.cY,this)));this.A.push(this.nd.$_s("onlineScreenChange",(0,g.B)(this.dU,this)))},SGa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.mE("MDX_CONFIG")||b;SEa();y6();r8||(r8=new i7(b?b.loungeApiHost:void 0),$Ea()&&(r8.o="/api/loungedev"));s8||(s8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ta("yt.mdx.remote.deferredProxies_",s8,void 0));OGa();var c=t8();if(!c){var d=new z7(r8);g.ta("yt.mdx.remote.screenService_",d,void 0);c=t8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);sGa(a,d,function(a){a?u8()&&U7(u8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.vG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ta("yt.mdx.remote.initialized_",!0,void 0),v8("Initializing: "+g.Hg(b)),w8.push(g.rG("yt-remote-cast2-availability-change",function(){g.vG("yt-remote-receiver-availability-change")})),w8.push(g.rG("yt-remote-cast2-receiver-selected",function(){x8(null);
g.vG("yt-remote-auto-connect","cast-selector-receiver")})),w8.push(g.rG("yt-remote-cast2-receiver-resumed",function(){g.vG("yt-remote-receiver-resumed","cast-selector-receiver")})),w8.push(g.rG("yt-remote-cast2-session-change",PGa)),w8.push(g.rG("yt-remote-connection-change",function(a){a?U7(u8(),"YouTube TV"):y8()||(U7(null,null),vGa())})),a=z8(),b.isAuto&&(a.id+="#dial"),g.uE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),v8(" -- with channel params: "+
g.Hg(a)),QGa(a),c.start(),u8()||RGa())},UGa=function(){var a=TGa();
R7()&&g.CH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},TGa=function(){var a=t8().nd.$_gos();
var b=A8();b&&B8()&&(t6(a,b)||a.push(b));return REa(a)},C8=function(){var a=VGa();
!a&&R7()&&uGa()&&(a={key:"cast-selector-receiver",name:uGa()});return a},VGa=function(){var a=TGa(),b=A8();
b||(b=y8());return g.Ja(a,function(a){return b&&p6(b,a.key)?!0:!1})},A8=function(){var a=u8();
if(!a)return null;var b=t8().De();return u6(b,a)},PGa=function(a){v8("remote.onCastSessionChange_: "+q6(a));
if(a){var b=A8();b&&b.id==a.id?U7(b.id,"YouTube TV"):(b&&D8(),E8(a,1))}else B8()&&D8()},D8=function(){S7()?P7().stopSession():N7("stopSession called before API ready.");
var a=B8();a&&(a.disconnect(1),F8(null))},G8=function(){var a=B8();
return!!a&&3!=a.getProxyState()},v8=function(a){m7("remote",a)},t8=function(){if(!H8){var a=g.y("yt.mdx.remote.screenService_");
H8=a?new q8(a):null}return H8},u8=function(){return g.y("yt.mdx.remote.currentScreenId_")},WGa=function(a){g.ta("yt.mdx.remote.currentScreenId_",a,void 0)},XGa=function(){return g.y("yt.mdx.remote.connectData_")},x8=function(a){g.ta("yt.mdx.remote.connectData_",a,void 0)},B8=function(){return g.y("yt.mdx.remote.connection_")},F8=function(a){var b=B8();
x8(null);a||WGa("");g.ta("yt.mdx.remote.connection_",a,void 0);s8&&((0,g.D)(s8,function(b){b(a)}),s8.length=0);
b&&!a?g.vG("yt-remote-connection-change",!1):!b&&a&&g.vG("yt-remote-connection-change",!0)},y8=function(){var a=g.EH();
if(!a)return null;var b=t8().De();return u6(b,a)},E8=function(a,b){A8()&&A8();
WGa(a.id);var c=new j8(r8,a,z8());c.connect(b,XGa());c.subscribe("beforeDisconnect",function(a){g.vG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){B8()&&F8(null)});
F8(c)},RGa=function(){var a=y8();
a?(v8("Resume connection to: "+q6(a)),E8(a,0)):(z6(),vGa(),v8("Skipping connecting because no session screen found."))},OGa=function(){var a=z8();
if(g.Yb(a)){a=x6();var b=g.CH("yt-remote-session-name")||"",c=g.CH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ta("yt.mdx.remote.channelParams_",a,void 0)}},z8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},QGa=function(a){a?(g.BH("yt-remote-session-app",a.app),g.BH("yt-remote-session-name",a.name)):(g.DH("yt-remote-session-app"),g.DH("yt-remote-session-name"));
g.ta("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.L.call(this);
this.D=a;this.A=b;this.B=new g.bG(this);g.M(this,this.B);this.B.R(b,"onCaptionsTrackListChanged",this.uT);this.B.R(b,"captionschanged",this.ZR);this.B.R(b,"captionssettingschanged",this.cG);this.B.R(b,"videoplayerreset",this.uq);this.B.R(b,"mdxautoplaycancel",this.jK);this.V=this.B.R(b,"onVolumeChange",this.eE);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.sE,this);c.subscribe("remotePlayerChange",this.en,this);c.subscribe("remoteQueueChange",this.uq,this);c.subscribe("autoplayUpNext",this.QD,
this);c.subscribe("previousNextChange",this.pE,this);c.subscribe("nowAutoplaying",this.hE,this);c.subscribe("autoplayDismissed",this.PD,this);this.suggestion=null;this.J=new g.AP(64);this.C=new g.Cu(this.YF,500,this);g.M(this,this.C);this.F=new g.Cu(this.ZF,1E3,this);g.M(this,this.F);this.L=new H6(this.DX,0,this);g.M(this,this.L);this.G={};this.M=new g.Cu(this.DG,1E3,this);g.M(this,this.M);this.K=new g.vl(this.cQ,1E3,this);g.M(this,this.K);this.O=g.A;this.cG();this.uq();this.en()},J8=function(a,b){var c=
a.D,d=a.A.getVideoData().lengthSeconds;
c.J=b||0;c.player.U("progresssync",b,d)},YGa=function(a){J8(a,0);
a.C.stop();K8(a,new g.AP(64))},M8=function(a,b){if(L8(a)&&!a.H){var c=null;
b&&(c={style:a.A.Wi()},g.fc(c,b));a.o.MF(a.A.getVideoData(1).videoId,c);a.G=d8(a.o).o}},N8=function(a,b){var c=a.A.mg();
if(c){var d=c.Be();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.dk;f=HEa(f);var n=d8(c);l=l||0;var p={videoId:k,currentIndex:l};$7(n,k,l);g.u(b)&&(Y7(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Hg(f));h8(c,"setPlaylist",p);e||f8(c,n);K8(a,new g.AP(1))},ZGa=function(a,b){if(b){var c=a.A.Cc("captions","tracklist",{pB:1});
c&&c.length?(a.A.Xd("captions","track",b),a.H=!1):(a.A.wk("captions"),a.H=!0)}else a.A.Xd("captions","track",{})},L8=function(a){return d8(a.o).videoId==a.A.getVideoData(1).videoId},K8=function(a,b){a.F.stop();
var c=a.J;if(!g.GP(c,b)){var d=g.W(b,2);d!=g.W(a.J,2)&&g.UT(a.A,d);a.J=b;$Ga(a.D,c,b)}},O8=function(a){g.V.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.$ra()]},{I:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.B=new g.SU(this,250);g.M(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);aHa(this,g.QT(a))},aHa=function(a,b){if(3==a.C.Ta()){var c={RECEIVER_NAME:a.C.Cc("remote","currentReceiver").name};
c=g.W(b,128)?g.KU("Error on $RECEIVER_NAME",c):b.sb()||g.W(b,4)?g.KU("Playing on $RECEIVER_NAME",c):g.KU("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},P8=function(a,b){g.sY.call(this,"Play on",0,a,b);
this.B=a;this.J={};this.R(a,"onMdxReceiversChange",this.L);this.R(a,"presentingplayerstatechange",this.L);this.L()},Q8=function(a){g.tU.call(this,a);
this.A={key:s6(),name:"This computer"};this.C=null;this.D=[];this.K=this.o=null;this.H=[this.A];this.B=this.A;this.F=new g.AP(64);this.J=0;this.G=-1;if(!g.qN(g.X(this.player))){a=this.player;var b=g.sI(a);b&&(b=b.Sm())&&(b=new P8(a,b),g.M(this,b));b=new O8(a);g.M(this,b);g.jU(a,b.element,4)}},$Ga=function(a,b,c){a.F=c;
a.player.U("presentingplayerstatechange",new g.LP(c,b))},R8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)D8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.mg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Qa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.dk,index:Math.max(a.player.uC(),0),currentTime:0==f?void 0:f};(d=HEa(d))&&(c.locationInfo=d);d=c}else d=null;v8("Connecting to: "+g.Hg(b));"cast-selector-receiver"==b.key?(x8(d||null),S7()?P7().setLaunchParams(d||
null):N7("setLaunchParams called before ready.")):!d&&G8()&&u8()==b.key?g.vG("yt-remote-connection-change",!0):(D8(),x8(d||null),d=t8().De(),(d=u6(d,b.key))&&E8(d,1))}},pFa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},R6={"'":"\\'"},bHa={},NEa={DZ:"atp",h4:"ska",z3:"que",L2:"mus",d4:"sus",P0:"dsp"};
n6.prototype.Ho=function(){var a=new n6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var A6,w6="",E6=B6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",hFa=B6("loadCastFramework")||B6("loadCastApplicationFramework"),rGa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(H6,g.L);g.h=H6.prototype;g.h.eL=function(a){this.C=arguments;this.o=!1;this.Ga?this.B=(0,g.H)()+this.Ed:this.Ga=g.Cg(this.D,this.Ed)};
g.h.stop=function(){this.Ga&&(g.Dg(this.Ga),this.Ga=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();H6.ga.X.call(this)};
g.h.fL=function(){this.B?(this.Ga=g.Cg(this.D,this.B-(0,g.H)()),this.B=null):(this.Ga=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};I6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
I6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=J6.prototype;g.h.Di=null;g.h.Nf=!1;g.h.ol=null;g.h.wx=null;g.h.Rk=null;g.h.Uj=null;g.h.yh=null;g.h.Yh=null;g.h.fj=null;g.h.Wc=null;g.h.Bn=0;g.h.Of=null;g.h.xr=null;g.h.zh=null;g.h.gm=-1;g.h.sF=!0;g.h.mi=!1;g.h.Et=0;g.h.Jq=null;var nFa={},M6={};g.h=J6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.DW=function(a){a=a.target;var b=this.Jq;b&&3==g.Kx(a)?b.Yl():this.OG(a)};
g.h.OG=function(a){try{if(a==this.Wc)a:{var b=g.Kx(this.Wc),c=this.Wc.A,d=this.Wc.getStatus();if(g.Jd&&!g.sc(10)||g.Ld&&!g.rc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.qf&&!g.Ox(this.Wc))break a;this.mi||4!=b||7==c||(8==c||0>=d?this.o.Gf(3):this.o.Gf(2));T6(this);var e=this.Wc.getStatus();this.gm=e;var f=g.Ox(this.Wc);(this.Nf=200==e)?(4==b&&P6(this),this.D?(oFa(this,b,f),g.qf&&this.Nf&&3==b&&(this.Y.W(this.A,"tick",this.zW),this.A.start())):O6(this,f),this.Nf&&!this.mi&&(4==b?this.o.rq(this):
(this.Nf=!1,L6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.zh=3,N6(13)):(this.zh=0,N6(14)),P6(this),Q6(this))}}catch(k){this.Wc&&g.Ox(this.Wc)}finally{}};
g.h.zW=function(){var a=g.Kx(this.Wc),b=g.Ox(this.Wc);this.Bn<b.length&&(T6(this),oFa(this,a,b),this.Nf&&4!=a&&L6(this))};
g.h.HV=function(a){S6((0,g.B)(this.GV,this,a),0)};
g.h.GV=function(a){this.mi||(T6(this),O6(this,a),L6(this))};
g.h.BE=function(a){S6((0,g.B)(this.FV,this,a),0)};
g.h.FV=function(a){this.mi||(P6(this),this.Nf=a,this.o.rq(this),this.o.Gf(4))};
g.h.cancel=function(){this.mi=!0;P6(this)};
g.h.XV=function(){this.ol=null;var a=(0,g.H)();0<=a-this.wx?(2!=this.Uj&&this.o.Gf(3),P6(this),this.zh=2,N6(18),Q6(this)):rFa(this,this.wx-a)};g.h=uFa.prototype;g.h.Ct=null;g.h.Ie=null;g.h.Kq=!1;g.h.IA=null;g.h.Vo=null;g.h.vu=null;g.h.Dt=null;g.h.bf=null;g.h.Mg=-1;g.h.fm=null;g.h.ul=null;g.h.connect=function(a){this.Dt=a;a=V6(this.o,null,this.Dt);N6(3);this.IA=(0,g.H)();var b=this.o.H;null!=b?(this.fm=b[0],(this.ul=b[1])?(this.bf=1,vFa(this)):(this.bf=2,X6(this))):(m6(a,"MODE","init"),this.Ie=new J6(this,void 0,void 0,void 0),this.Ie.Di=this.Ct,K6(this.Ie,a,!1,null,!0),this.bf=0)};
g.h.kK=function(a){if(a)this.bf=2,X6(this);else{N6(4);var b=this.o;b.Zf=b.ph.Mg;d7(b,9)}a&&this.Gf(2)};
g.h.Ms=function(a){return this.o.Ms(a)};
g.h.abort=function(){this.Ie&&(this.Ie.cancel(),this.Ie=null);this.Mg=-1};
g.h.HA=function(){return!1};
g.h.tE=function(a,b){this.Mg=a.gm;if(0==this.bf)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Zf=this.Mg;d7(c,2);return}this.fm=c[0];this.ul=c[1]}else c=this.o,c.Zf=this.Mg,d7(c,2);else if(2==this.bf)if(this.Kq)N6(7),this.vu=(0,g.H)();else if("11111"==b){if(N6(6),this.Kq=!0,this.Vo=(0,g.H)(),c=this.Vo-this.IA,!g.Jd||g.sc(10)||500>c)this.Mg=200,this.Ie.cancel(),N6(12),W6(this.o,this,!0)}else N6(8),this.Vo=this.vu=(0,g.H)(),this.Kq=!1};
g.h.rq=function(){this.Mg=this.Ie.gm;if(this.Ie.Nf)0==this.bf?this.ul?(this.bf=1,vFa(this)):(this.bf=2,X6(this)):2==this.bf&&((!g.Jd||g.sc(10)?!this.Kq:200>this.vu-this.Vo)?(N6(11),W6(this.o,this,!1)):(N6(12),W6(this.o,this,!0)));else{0==this.bf?N6(9):2==this.bf&&N6(10);var a=this.o;a.Zf=this.Mg;d7(a,2)}};
g.h.qn=function(){return this.o.qn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Gf=function(a){this.o.Gf(a)};g.h=Y6.prototype;g.h.Kl=null;g.h.ke=null;g.h.yc=null;g.h.Bt=null;g.h.Zo=null;g.h.dz=null;g.h.pp=null;g.h.Ym=0;g.h.rR=0;g.h.Dd=null;g.h.sh=null;g.h.zg=null;g.h.pi=null;g.h.ph=null;g.h.vr=null;g.h.lk=-1;g.h.DB=-1;g.h.Zf=-1;g.h.Kj=0;g.h.xj=0;g.h.oi=8;var e7=new g.Qf;g.C(xFa,g.of);g.C(yFa,g.of);g.C(zFa,g.of);g.h=Y6.prototype;g.h.connect=function(a,b,c,d,e){N6(0);this.Bt=b;this.Kl=c||{};d&&g.u(e)&&(this.Kl.OSID=d,this.Kl.OAID=e);this.F?(S6((0,g.B)(this.zz,this,a),100),DFa(this)):this.zz(a)};
g.h.zz=function(a){this.ph=new uFa(this);this.ph.Ct=null;this.ph.A=this.D;this.ph.connect(a)};
g.h.HA=function(){return 0==this.o};
g.h.zE=function(a){this.sh=null;GFa(this,a)};
g.h.yE=function(){this.zg=null;this.yc=new J6(this,this.B,"rpc",this.G);this.yc.Di=null;this.yc.Et=0;var a=this.dz.clone();g.cn(a,"RID","rpc");g.cn(a,"SID",this.B);g.cn(a,"CI",this.vr?"0":"1");g.cn(a,"AID",this.lk);Z6(this,a);if(!g.Jd||g.sc(10))g.cn(a,"TYPE","xmlhttp"),K6(this.yc,a,!0,this.pp,!1);else{g.cn(a,"TYPE","html");var b=this.yc,c=!!this.pp;b.Uj=3;b.yh=l6(a.clone());qFa(b,c)}};
g.h.tE=function(a,b){if(0!=this.o&&(this.yc==a||this.ke==a))if(this.Zf=a.gm,this.ke==a&&3==this.o)if(7<this.oi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.wa(c)&&3==c.length)if(0==c[0])a:{if(!this.zg){if(this.yc)if(this.yc.Rk+3E3<this.ke.Rk)a7(this),this.yc.cancel(),this.yc=null;else break a;c7(this);N6(19)}}else this.DB=c[1],0<this.DB-this.lk&&37500>c[2]&&this.vr&&0==this.xj&&!this.pi&&(this.pi=S6((0,g.B)(this.UR,this),6E3));else d7(this,11)}else b!=bHa.F_.o&&d7(this,11);else if(this.yc==a&&
a7(this),!g.F(b)){c=this.D.parse(b);g.wa(c);for(var d=0;d<c.length;d++){var e=c[d];this.lk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.pp=e[2],e=e[3],null!=e?this.oi=e:this.oi=6,this.o=3,this.Dd&&this.Dd.pz(),this.dz=V6(this,this.qn()?this.pp:null,this.Bt),HFa(this)):"stop"==e[0]&&d7(this,7):3==this.o&&("stop"==e[0]?d7(this,7):"noop"!=e[0]&&this.Dd&&this.Dd.oz(e),this.xj=0)}}};
g.h.UR=function(){null!=this.pi&&(this.pi=null,this.yc.cancel(),this.yc=null,c7(this),N6(20))};
g.h.rq=function(a){if(this.yc==a){a7(this);this.yc=null;var b=2}else if(this.ke==a)this.ke=null,b=1;else return;this.Zf=a.gm;if(0!=this.o)if(a.Nf)1==b?(b=(0,g.H)()-a.Rk,e7.dispatchEvent(new yFa(e7,a.fj?a.fj.length:0,b,this.Kj)),$6(this),this.C.length=0):HFa(this);else{var c=a.zh,d;if(!(d=3==c||7==c||0==c&&0<this.Zf)){if(d=1==b)this.ke||this.sh||1==this.o||2<=this.Kj?d=!1:(this.sh=S6((0,g.B)(this.zE,this,a),IFa(this,this.Kj)),this.Kj++,d=!0);d=!(d||2==b&&c7(this))}if(d)switch(c){case 1:d7(this,5);
break;case 4:d7(this,10);break;case 3:d7(this,6);break;case 7:d7(this,12);break;default:d7(this,2)}}};
g.h.GK=function(a){if(!g.Na(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.sX=function(a){a?N6(2):(N6(1),JFa(this,8))};
g.h.Ms=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Ex;a.H=!1;return a};
g.h.isActive=function(){return!!this.Dd&&this.Dd.isActive(this)};
g.h.Gf=function(a){e7.dispatchEvent(new zFa(e7,a))};
g.h.qn=function(){return!(!g.Jd||g.sc(10))};
g.h=KFa.prototype;g.h.pz=function(){};
g.h.oz=function(){};
g.h.nz=function(){};
g.h.xs=function(){};
g.h.nA=function(){return{}};
g.h.isActive=function(){return!0};g.C(f7,g.L);g.h=f7.prototype;g.h.xV=function(){this.Ed=Math.min(3E5,2*this.Ed);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Ed+15E3*Math.random();g.Du(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Ed=5E3};g.C(g7,KFa);g.h=g7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.de=function(a){return this.B.de(a)};
g.h.U=function(a,b){return this.B.U.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.mf(this.B),NFa(this),g.mf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new Y6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.Dd=null);d.Dd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.lk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):h7(this)&&EFa(this.o,c)};
g.h.pz=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)EFa(this.o,a[b])}this.U("handlerOpened")};
g.h.nz=function(a){var b=2==a&&401==this.o.Zf;4==a||b||this.A.start();this.U("handlerError",a)};
g.h.xs=function(a){if(!this.A.isActive())this.U("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.nA=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.fc(a,this.D);return a};
g.h.oz=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),CFa(this.o)):this.U("handlerMessage",new LFa(a[0],a[1]))};
g.h.YX=function(){this.A.isActive();var a=this.o,b=0;a.yc&&b++;a.ke&&b++;0!=b||this.connect(this.D,this.C)};i7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
i7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
i7.prototype.D=function(a){a(Error("request timed out"))};var VFa=(0,g.H)(),l7=null,o7=Array(50),n7=-1,p7=!1;g.C(q7,g.eG);q7.prototype.De=function(){return this.o};
q7.prototype.contains=function(a){return!!t6(this.o,a)};
q7.prototype.get=function(a){return a?u6(this.o,a):null};
q7.prototype.info=function(a){m7(this.G,a)};g.C(r7,g.eG);var cHa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=r7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Ga)&&this.VG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Ga)||(g.zE(this.Ga),this.Ga=window.NaN)};
g.h.X=function(){this.stop();r7.ga.X.call(this)};
g.h.VG=function(){this.Ga=window.NaN;this.o=g.OE(j7(this.F,"/pairing/get_screen"),{method:"POST",Ub:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.B)(this.aY,this),onError:(0,g.B)(this.ZX,this),Id:(0,g.B)(this.bY,this)})};
g.h.aY=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.U("pairingComplete",new o6(c))};
g.h.ZX=function(a){this.o=null;a.status&&404==a.status?this.A>=cHa.length?this.U("pairingFailed",Error("DIAL polling timed out")):(a=cHa[this.A],this.Ga=g.xE((0,g.B)(this.VG,this),a),this.A++):this.U("pairingFailed",Error("Server error "+a.status))};
g.h.bY=function(){this.o=null;this.U("pairingFailed",Error("Server not responding"))};g.C(t7,q7);g.h=t7.prototype;g.h.start=function(){s7(this)&&this.U("screenChange");!g.CH("yt-remote-lounge-token-expiration")&&ZFa(this);g.zE(this.A);this.A=g.xE((0,g.B)(this.start,this),1E4)};
g.h.add=function(a,b){s7(this);WFa(this,a);u7(this,!1);this.U("screenChange");b(a);a.token||ZFa(this)};
g.h.remove=function(a,b){var c=s7(this);YFa(this,a)&&(u7(this,!1),c=!0);b(a);c&&this.U("screenChange")};
g.h.rr=function(a,b,c,d){var e=s7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,u7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.U("screenChange")};
g.h.X=function(){g.zE(this.A);t7.ga.X.call(this)};
g.h.sL=function(a){s7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}u7(this,!b);b&&m7(this.G,"Missed "+b+" lounge tokens.")};
g.h.rL=function(a){m7(this.G,"Requesting lounge tokens failed: "+a)};g.C(w7,g.eG);g.h=w7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.CH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?y7(this):(this.C=(0,g.H)()+3E5,g.BH("yt-remote-fast-check-period",this.C),this.xw())};
g.h.isEmpty=function(){return g.Yb(this.o)};
g.h.update=function(){v7("Updating availability on schedule.");var a=this.F(),b=g.Ib(this.o,function(b,d){return b&&!!u6(a,d)},this);
x7(this,b)};
g.h.X=function(){g.zE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);w7.ga.X.call(this)};
g.h.xw=function(){g.zE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=bGa(this);if(g.Nb(a)){var b=j7(this.D,"/pairing/get_screen_availability");this.A=k7(this.D,b,{lounge_token:g.Qb(a).join(",")},(0,g.B)(this.fV,this,a),(0,g.B)(this.eV,this))}else x7(this,{}),y7(this)};
g.h.fV=function(a,b){this.A=null;var c=g.Qb(bGa(this));if(g.fb(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;x7(this,d);y7(this)}else this.sc("Changing Screen set during request."),this.xw()};
g.h.eV=function(a){this.sc("Screen availability failed: "+a);this.A=null;y7(this)};
g.h.sc=function(a){m7("OnlineScreenService",a)};g.C(z7,q7);g.h=z7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.U("screenChange"),this.A.isEmpty()||this.U("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.rr=function(a,b,c,d){this.B.contains(a)?this.B.rr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,m7(this.G,a),d(Error(a)))};
g.h.De=function(a){return a?this.o:g.Va(this.o,(0,g.Yd)(this.C,function(a){return!this.contains(a)},this))};
g.h.WG=function(){return(0,g.Yd)(this.De(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.XG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new r7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.B)(function(a){g.mf(f);d(A7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.mf(f);e(a)});
f.start();return(0,g.B)(f.stop,f)};
g.h.dY=function(a,b,c,d){g.OE(j7(this.F,"/pairing/get_screen"),{method:"POST",Ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(a,d){var e=new o6(d.screen||{});if(!e.name||fGa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);fGa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(A7(this,e))},this),
onError:(0,g.B)(function(a){d(Error("pairing request failed: "+a.status))},this),
Id:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.mf(this.B);g.mf(this.A);z7.ga.X.call(this)};
g.h.HL=function(){gGa(this);this.U("screenChange");this.A.update()};
z7.prototype.dispose=z7.prototype.dispose;g.C(C7,g.eG);g.h=C7.prototype;g.h.tq=function(a){this.B=a;this.U("sessionScreen",this.B)};
g.h.He=function(a){this.la()||(a&&D7(this,""+a),this.B=null,this.U("sessionScreen",null))};
g.h.info=function(a){m7(this.M,a)};
g.h.ZG=function(){return null};
g.h.Gw=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){D7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Gw("");C7.ga.X.call(this)};g.C(E7,C7);g.h=E7.prototype;g.h.Fw=function(a){if(this.o){if(this.o==a)return;D7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);iGa(this)};
g.h.nk=function(a){this.info("launchWithParams no-op for Cast: "+g.Hg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.B)(function(){this.He()},this),(0,g.B)(function(){this.He(Error("Failed to stop receiver app."))},this)):this.He(Error("Stopping cast device witout session."))};
g.h.Gw=g.A;g.h.X=function(){this.info("disposeInternal");g.zE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;E7.ga.X.call(this)};
g.h.jW=function(a,b){if(!this.la())if(b){var c=g.yx(b);if(g.za(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Hg(c));switch(d){case "mdxSessionStatus":hGa(this,c.screenId);break;default:D7(this,"Unknown youtube message: "+d)}}else D7(this,"Unable to parse message.")}else D7(this,"No data in message.")};
g.h.xA=function(a,b,c,d){eGa(this.J,this.A.label,a,this.A.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(D7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.xE((0,g.B)(this.xA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.ZG=function(){return this.o};
g.h.eY=function(a){this.la()||a||(D7(this,"Cast session died."),this.He())};g.C(F7,C7);g.h=F7.prototype;g.h.Fw=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.nk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.A;g.zE(this.F);this.C?this.C.stop((0,g.B)(this.He,this,null),(0,g.B)(this.He,this,"Failed to stop DIAL device.")):this.He()};
g.h.X=function(){this.o();this.o=g.A;g.zE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;F7.ga.X.call(this)};
g.h.hY=function(a){this.la()||a||(D7(this,"DIAL session died."),this.o(),this.o=g.A,this.He())};
g.h.gu=function(a){this.K=s6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,kGa(this));a(b);jGa(this)}else this.G=(0,g.B)(function(){g.zE(this.F);this.G=g.A;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,kGa(this));a(b);jGa(this)},this),this.F=g.xE((0,g.B)(function(){this.G()},this),100)};
g.h.VM=function(a,b,c){eGa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.B)(function(a){a&&a.token?(this.tq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.gu(b,c)},this),(0,g.B)(function(a){D7(this,"Failed to get DIAL screen: "+a);
this.gu(b,c)},this))};g.C(G7,C7);G7.prototype.stop=function(){this.He()};
G7.prototype.Fw=g.A;G7.prototype.nk=function(){g.zE(this.o);this.o=window.NaN;var a=u6(this.J.De(),this.A.label);a?this.tq(a):this.He(Error("No such screen"))};
G7.prototype.X=function(){g.zE(this.o);this.o=window.NaN;G7.ga.X.call(this)};g.C(H7,g.eG);g.h=H7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.B)(this.vE,this),(0,g.B)(this.NU,this),d,e);c.customDialLaunchCallback=(0,g.B)(this.ES,this);window.chrome.cast.initialize(c,
(0,g.B)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),SFa(),this.A.subscribe("onlineScreenChange",(0,g.B)(this.YG,this)),this.B=mGa(this),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.sc("Failed to set initial custom receivers: "+g.Hg(a))},this)),this.U("yt-remote-cast2-availability-change",J7(this)),b(!0))},this),(0,g.B)(function(a){this.sc("Failed to initialize API: "+g.Hg(a));
b(!1)},this))};
g.h.bX=function(a,b){I7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)I7("Unsetting old screen status: "+this.o.A.friendlyName),K7(this,null)}if(a&&b){if(!this.o){c=u6(this.A.De(),a);if(!c){I7("setConnectedScreenStatus: Unknown screen.");return}var d=lGa(this,c);d||(I7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.sc("Failed to set initial custom receivers: "+g.Hg(a))},this)));
I7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);K7(this,new G7(this.A,d),!0)}this.o.Gw(b)}else I7("setConnectedScreenStatus: no screen.")};
g.h.cX=function(a){this.la()?this.sc("Setting connection data on disposed cast v2"):this.o?this.o.nk(a):this.sc("Setting connection data without a session")};
g.h.gY=function(){this.la()?this.sc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),K7(this,null)):I7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.B)(this.vE,this),(0,g.B)(this.jV,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.B)(this.YG,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Ta(g.y("yt.mdx.remote.debug.handlers_")||[],PFa);g.mf(this.o);H7.ga.X.call(this)};
g.h.sc=function(a){m7("Controller",a)};
g.h.wE=function(a,b){this.o==a&&(b||K7(this,null),this.U("yt-remote-cast2-session-change",b))};
g.h.JU=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),I7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)I7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{I7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.U("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:K7(this,
new G7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:K7(this,new F7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:K7(this,new E7(this.A,a));break;default:this.sc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.sc("Stopping receiver w/o session: "+a.friendlyName)}else this.sc("onReceiverAction_ called without receiver.")};
g.h.ES=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.sc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.sc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return I7("Reselecting dial screen."),
this.U("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.sc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);K7(this,new F7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.B)(b.VM,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.B)(b.gu,b))};
g.h.vE=function(a){if(!this.la()){I7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)I7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),K7(this,new E7(this.A,b),!0);else{this.sc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=u6(this.A.De(),c.label);
d&&p6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(I7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.mf(this.o),this.o=new E7(this.A,b),this.o.subscribe("sessionScreen",(0,g.B)(this.wE,this,this.o)),this.o.nk(null));this.o.Fw(a)}}};
g.h.fY=function(){return this.o?this.o.ZG():null};
g.h.jV=function(a){this.la()||(this.sc("Failed to estabilish a session: "+g.Hg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&K7(this,null))};
g.h.NU=function(a){I7("Receiver availability updated: "+a);if(!this.la()){var b=J7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;J7(this)!=b&&this.U("yt-remote-cast2-availability-change",J7(this))}};
g.h.YG=function(){this.la()||(this.B=mGa(this),I7("Updating custom receivers: "+g.Hg(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(){this.sc("Failed to set custom receivers.")},this)),this.U("yt-remote-cast2-availability-change",J7(this)))};
H7.prototype.setLaunchParams=H7.prototype.cX;H7.prototype.setConnectedScreenStatus=H7.prototype.bX;H7.prototype.stopSession=H7.prototype.gY;H7.prototype.getCastSession=H7.prototype.fY;H7.prototype.requestSession=H7.prototype.requestSession;H7.prototype.init=H7.prototype.init;H7.prototype.dispose=H7.prototype.dispose;var Q7=[];g.h=V7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";W7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.eg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!(0,window.isNaN)(this.B))};
g.h.sb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+X7(this):this.H};
g.h.clone=function(){return new V7(a8(this))};g.C(c8,g.eG);g.h=c8.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.A,i8(this,"play")):h8(this,"play"),g8(this,1,Z7(d8(this))),this.U("remotePlayerChange")):e8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.A,i8(this,"pause")):h8(this,"pause"),g8(this,2,Z7(d8(this))),this.U("remotePlayerChange")):e8(this,this.pause)};
g.h.UG=function(a){if(1==this.o){if(this.A){var b=d8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.sb()||3==b.playerState?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.A,i8(this,"seekTo",{newTime:a}))}else h8(this,"seekTo",{newTime:a});g8(this,3,a);this.U("remotePlayerChange")}else e8(this,g.Ca(this.UG,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.A,i8(this,"stopVideo")):h8(this,"stopVideo");var a=d8(this);a.index=-1;a.videoId="";W7(a);f8(this,a);this.U("remotePlayerChange")}else e8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=d8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.B)(function(){m7("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.sc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.B)(function(){m7("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.sc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);h8(this,"setVolume",e)}c.muted=b;c.volume=a;f8(this,c)}else e8(this,g.Ca(this.setVolume,a,b))};
g.h.MF=function(a,b){if(1==this.o){var c=d8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Hg(b.style),g.fc(d,c.o));h8(this,"setSubtitlesTrack",d);f8(this,c)}else e8(this,g.Ca(this.MF,a,b))};
g.h.Dx=function(a,b){if(1==this.o){h8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Nb.id});var c=d8(this);c.audioTrackId=b.Nb.id;f8(this,c)}else e8(this,g.Ca(this.Dx,a,b))};
g.h.TG=function(a,b){if(1==this.o){if(a&&b){var c=d8(this);$7(c,a,b);f8(this,c)}h8(this,"previous")}else e8(this,g.Ca(this.TG,a,b))};
g.h.SG=function(a,b){if(1==this.o){if(a&&b){var c=d8(this);$7(c,a,b);f8(this,c)}h8(this,"next")}else e8(this,g.Ca(this.SG,a,b))};
g.h.Rz=function(){1==this.o?h8(this,"dismissAutoplay"):e8(this,this.Rz)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.U("proxyStateChange",a,this.o)}c8.ga.dispose.call(this)};
g.h.X=function(){zGa(this);this.C=null;this.D.clear();b8(this,null);c8.ga.X.call(this)};
g.h.Ex=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.TC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.EU=function(a,b){this.U(a,b)};
g.h.bS=function(a){if(!a)this.bn(null),b8(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=d8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)m7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,f8(this,b)}};
g.h.bn=function(a){m7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),AGa(this),this.U("remotePlayerChange")};
g.h.aS=function(a){a?(AGa(this),this.U("remotePlayerChange")):this.bn(null)};
g.h.oS=function(){var a=wGa();a&&b8(this,a)};
g.h.sc=function(a){m7("CP",a)};g.C(j8,g.eG);g.h=j8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.jb.listId=c);this.jb.videoId=d;this.jb.index=k||0;this.jb.state=3;Y7(this.jb,m);this.C="UNSUPPORTED";k8("Connecting with setPlaylist and params: "+g.Hg(l));this.o.connect({method:"setPlaylist",
params:g.Hg(l)},a,VEa())}else k8("Connecting without params"),this.o.connect({},a,VEa());CGa(this)};
g.h.dispose=function(){this.la()||(this.U("beforeDispose"),l8(this,3));j8.ga.dispose.call(this)};
g.h.X=function(){m8(this);o8(this);n8(this);g.zE(this.J);this.J=window.NaN;g.zE(this.K);this.K=window.NaN;this.B=null;g.PF(this.V);this.V.length=0;this.o.dispose();j8.ga.X.call(this);this.C=this.G=this.A=this.jb=this.o=null};
g.h.jL=function(){this.F(2)};
g.h.fS=function(){k8("Channel opened");this.O&&(this.O=!1,n8(this),this.M=g.xE((0,g.B)(function(){k8("Timing out waiting for a screen.");this.F(1)},this),15E3));
ZEa(MFa(this.o),this.ba)};
g.h.cS=function(){k8("Channel closed");(0,window.isNaN)(this.D)?z6(!0):z6();this.dispose()};
g.h.dS=function(a){z6();(0,window.isNaN)(this.H())?(k8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,k8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),l8(this,2))};
g.h.eS=function(a){a.params?k8("Received: action="+a.action+", params="+g.Hg(a.params)):k8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.yx(a.params.devices);this.A=(0,g.J)(a,function(a){return new n6(a)});
a=!!g.Ja(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
FGa(this,a);break;case "loungeScreenDisconnected":g.Ua(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
FGa(this,!1);break;case "remoteConnected":var b=new n6(g.yx(a.params.device));g.Ja(this.A,function(a){return b?a.id==b.id:!1})||g.Ra(this.A,b);
break;case "remoteDisconnected":b=new n6(g.yx(a.params.device));g.Ua(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":HGa(this,a);break;case "nowPlaying":JGa(this,a);break;case "onStateChange":IGa(this,a);break;case "onAdStateChange":KGa(this,a);break;case "onVolumeChanged":LGa(this,a);break;case "onSubtitlesTrackChanged":GGa(this,a);break;case "nowAutoplaying":MGa(this,a);break;case "autoplayDismissed":this.U("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.U("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.U("autoplayModeChange",this.C);"DISABLED"==this.C&&this.U("autoplayDismissed");break;case "onHasPreviousNextChanged":NGa(this,a);break;case "requestAssistedSignIn":this.U("assistedSignInRequested",a.params.authCode);break;default:k8("Unrecognized action: "+a.action)}};
g.h.LW=function(){if(this.B){var a=this.B;this.B=null;this.jb.videoId!=a&&p8(this,"getNowPlaying")}};
j8.prototype.subscribe=j8.prototype.subscribe;j8.prototype.unsubscribeByKey=j8.prototype.de;j8.prototype.ia=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?h7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
j8.prototype.getProxyState=j8.prototype.ia;j8.prototype.F=function(a){k8("Disconnecting with "+a);m8(this);this.U("beforeDisconnect",a);1==a&&z6();NFa(this.o,a);this.dispose()};
j8.prototype.disconnect=j8.prototype.F;j8.prototype.fa=function(){var a=this.jb;this.B&&(a=this.jb.clone(),$7(a,this.B,a.index));return a8(a)};
j8.prototype.getPlayerContextData=j8.prototype.fa;
j8.prototype.ma=function(a){var b=new V7(a);b.videoId&&b.videoId!=this.jb.videoId&&(this.B=b.videoId,g.zE(this.J),this.J=g.xE((0,g.B)(this.LW,this),5E3));var c=[];this.jb.listId==b.listId&&this.jb.videoId==b.videoId&&this.jb.index==b.index||c.push("remoteQueueChange");this.jb.playerState==b.playerState&&this.jb.volume==b.volume&&this.jb.muted==b.muted&&Z7(this.jb)==Z7(b)&&g.Hg(this.jb.o)==g.Hg(b.o)||c.push("remotePlayerChange");this.jb.reset(a);(0,g.D)(c,function(a){this.U(a)},this)};
j8.prototype.setPlayerContextData=j8.prototype.ma;j8.prototype.Z=function(){var a=this.o.F.id,b=g.Ja(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
j8.prototype.getOtherConnectedRemoteId=j8.prototype.Z;j8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():window.NaN};
j8.prototype.getReconnectTimeout=j8.prototype.H;j8.prototype.aa=function(){return this.C||"UNSUPPORTED"};
j8.prototype.getAutoplayMode=j8.prototype.aa;j8.prototype.da=function(){return this.G||""};
j8.prototype.getAutoplayVideoId=j8.prototype.da;j8.prototype.wa=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.Eu(a.o);a.start()}};
j8.prototype.reconnect=j8.prototype.wa;j8.prototype.ka=function(a,b){p8(this,a,b);EGa(this)};
j8.prototype.sendMessage=j8.prototype.ka;g.C(q8,q7);g.h=q8.prototype;g.h.De=function(a){return this.nd.$_gs(a)};
g.h.contains=function(a){return!!this.nd.$_c(a)};
g.h.get=function(a){return this.nd.$_g(a)};
g.h.start=function(){this.nd.$_st()};
g.h.add=function(a,b,c){this.nd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.nd.$_r(a,b,c)};
g.h.rr=function(a,b,c,d){this.nd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.nd.$_ubk(this.A[a]);this.A.length=0;this.nd=null;q8.ga.X.call(this)};
g.h.cY=function(){this.U("screenChange")};
g.h.dU=function(){this.U("onlineScreenChange")};
z7.prototype.$_st=z7.prototype.start;z7.prototype.$_gspc=z7.prototype.dY;z7.prototype.$_gsppc=z7.prototype.XG;z7.prototype.$_c=z7.prototype.contains;z7.prototype.$_g=z7.prototype.get;z7.prototype.$_a=z7.prototype.add;z7.prototype.$_un=z7.prototype.rr;z7.prototype.$_r=z7.prototype.remove;z7.prototype.$_gs=z7.prototype.De;z7.prototype.$_gos=z7.prototype.WG;z7.prototype.$_s=z7.prototype.subscribe;z7.prototype.$_ubk=z7.prototype.de;var r8=null,s8=null,H8=null,w8=[];g.t(I8,g.L);g.h=I8.prototype;
g.h.X=function(){g.L.prototype.X.call(this);this.C.stop();this.F.stop();this.L.stop();this.O();this.o.unsubscribe("proxyStateChange",this.sE,this);this.o.unsubscribe("remotePlayerChange",this.en,this);this.o.unsubscribe("remoteQueueChange",this.uq,this);this.o.unsubscribe("autoplayUpNext",this.QD,this);this.o.unsubscribe("previousNextChange",this.pE,this);this.o.unsubscribe("nowAutoplaying",this.hE,this);this.o.unsubscribe("autoplayDismissed",this.PD,this);this.o=this.D=null};
g.h.MC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(L8(this)){if(!d8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":d8(this.o).sb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Yl(c[0],c[1]);break;case "control_subtitles_set_track":M8(this,c[0]);break;case "control_set_audio_track":c=c[0],L8(this)&&this.o.Dx(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();N8(this,0==c?void 0:c);break;case "control_seek":N8(this,c[0]);break;case "control_subtitles_set_track":M8(this,c[0]);break;case "control_set_audio_track":c=c[0],L8(this)&&this.o.Dx(this.A.getVideoData(1).videoId,c)}};
g.h.ZR=function(a){this.L.eL(a)};
g.h.DX=function(a){this.MC("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.cG=function(){var a=this.A.Cc("captions","track");g.Yb(a)||M8(this,a)};
g.h.eE=function(a){if(L8(this)){this.o.unsubscribe("remotePlayerChange",this.en,this);var b=Math.round(a.volume);a=!!a.muted;var c=d8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.en,this)}};
g.h.uT=function(){g.Yb(this.G)||ZGa(this,this.G);this.H=!1};
g.h.sE=function(a,b){this.F.stop();2==b&&this.ZF()};
g.h.en=function(){if(L8(this)){this.C.stop();var a=d8(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.G=1;break;case 1082:case 1083:this.D.G=0;break;default:this.D.G=-1}switch(a.playerState){case 1081:case 1:K8(this,new g.AP(8));this.YF();break;case 1085:case 3:K8(this,new g.AP(9));break;case 1083:case 0:K8(this,new g.AP(2));this.K.stop();J8(this,this.A.getVideoData().lengthSeconds);break;case 1084:K8(this,new g.AP(4));break;case 2:K8(this,new g.AP(4));J8(this,Z7(a));
break;case -1:K8(this,new g.AP(64));break;case -1E3:K8(this,new g.AP(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=d8(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.G=a,ZGa(this,a));a=d8(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.DG()}else YGa(this)};
g.h.pE=function(){this.A.U("mdxpreviousnextchange")};
g.h.uq=function(){L8(this)||YGa(this)};
g.h.jK=function(){this.o.Rz()};
g.h.QD=function(a){a&&(a=g.OE("/watch_queue_ajax",{method:"GET",dd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.B)(this.KV,this)}))&&(this.O=(0,g.B)(a.abort,a))};
g.h.KV=function(a,b){var c=new g.RO(g.X(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.U("mdxautoplayupnext",c)};
g.h.hE=function(a){(0,window.isNaN)(a)||this.A.U("mdxnowautoplaying",a)};
g.h.PD=function(){this.A.U("mdxautoplaycanceled")};
g.h.cQ=function(a,b){-1==d8(this.o).playerState?N8(this,a):b&&this.o.UG(a)};
g.h.DG=function(){if(L8(this)){var a=d8(this.o);this.B.Ja(this.V);a.muted?this.A.mute():this.A.ng();this.A.setVolume(a.volume);this.V=this.B.R(this.A,"onVolumeChange",this.eE)}};
g.h.YF=function(){this.C.stop();if(!this.o.la()){var a=d8(this.o);a.sb()&&K8(this,new g.AP(8));J8(this,Z7(a));this.C.start()}};
g.h.ZF=function(){this.F.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.F.start()};g.t(O8,g.V);O8.prototype.D=function(a){aHa(this,a.state)};g.t(P8,g.sY);P8.prototype.L=function(){var a=this.B.Cc("remote","receivers");a&&1<a.length&&!this.B.Cc("remote","quickCast")?(this.J=g.ib(a,this.F,this),g.tY(this,(0,g.J)(a,this.F)),a=this.B.Cc("remote","currentReceiver"),this.Ff(this.F(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.F=function(a){return a.key};
P8.prototype.Ef=function(a){return"cast-selector-receiver"==a?"Cast...":this.J[a].name};
P8.prototype.Gd=function(a){g.sY.prototype.Gd.call(this,a);this.B.Xd("remote","currentReceiver",this.J[a]);this.D.Tb()};g.t(Q8,g.tU);g.h=Q8.prototype;g.h.create=function(){SGa(g.hN(g.X(this.player)));this.D.push(g.rG("yt-remote-before-disconnect",this.VR,this));this.D.push(g.rG("yt-remote-connection-change",this.OU,this));this.D.push(g.rG("yt-remote-receiver-availability-change",this.qE,this));this.D.push(g.rG("yt-remote-auto-connect",this.MU,this));this.D.push(g.rG("yt-remote-receiver-resumed",this.LU,this));this.qE()};
g.h.load=function(){this.player.Zu();g.tU.prototype.load.call(this);this.C=new I8(this,this.player,this.o);var a=(a=XGa())?a.currentTime:0;var b=G8()?new c8(B8(),void 0):null;0==a&&b&&(a=Z7(d8(b)));0!=a&&(this.J=a||0,this.player.U("progresssync",a,void 0));$Ga(this,this.F,this.F);g.M_(this.player.app,6)};
g.h.unload=function(){this.player.U("mdxautoplaycanceled");this.B=this.A;g.nf(this.C,this.o);this.o=this.C=null;g.tU.prototype.unload.call(this);g.M_(this.player.app,5)};
g.h.X=function(){g.sG(this.D);g.tU.prototype.X.call(this)};
g.h.Rm=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.MC.apply(this.C,[a].concat(g.ea(c)))};
g.h.ZK=function(){return this.loaded?this.C.suggestion:null};
g.h.eg=function(){return this.o?d8(this.o).eg:!1};
g.h.hasNext=function(){return this.o?d8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.QP=function(){var a=d8(this.o),b=this.player.getVideoData();return{allowSeeking:g.X(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Lc():!a.isAdPlaying()&&this.player.Lc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+X7(a):a.B,isPeggedToLive:1>=(a.D?a.A+X7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+X7(a):a.A,seekableStart:0<a.C?a.C+X7(a):a.C}};
g.h.RP=function(){this.o&&this.o.SG()};
g.h.SP=function(){this.o&&this.o.TG()};
g.h.VR=function(a){1==a&&(this.K=this.o?d8(this.o):null)};
g.h.OU=function(){var a=G8()?new c8(B8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.mf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.player.getVideoData().videoId&&this.player.sC(a.videoId,Z7(a)));this.player.U("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.qE=function(){this.H=[this.A].concat(UGa());var a=C8()||this.A;R8(this,a);this.player.ya("onMdxReceiversChange")};
g.h.MU=function(){var a=C8();R8(this,a)};
g.h.LU=function(){this.B=C8()};
g.h.PP=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?T7():R8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&T7(),!0):!1}};
g.h.TP=function(){h8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ec=function(){return!1};g.sX.remote=Q8;})(_yt_player);
